/**
 * The parity ledger (D20 / R1).
 *
 * Two lists, two very different meanings:
 *
 *  - NO_CONTROL_BY_DESIGN: keys the Tkinter application itself never put on
 *    screen. Each carries the reason, taken from docs/INVENTAIRE_REGLAGES.md.
 *    This list is stable; it shrinks only if a key is deleted outright.
 *
 *  - NOT_YET_PORTED: keys that DO have a control in Tkinter and do not have
 *    one here yet. This list is temporary and MUST shrink at every chantier.
 *    A key removed from it can never come back: that would be a regression
 *    dressed up as bookkeeping.
 *
 * Both lists are generated from DEFAULT_CONFIG, never hand-copied: the
 * inventory document dates from v207 and DEFAULT_CONFIG has grown since.
 */

/** Defined in DEFAULT_CONFIG, never shown by the Tkinter application either. */
export const NO_CONTROL_BY_DESIGN: Record<string, string> = {
  output_dir: "internal fallback, mirrors output_dir_clips",
  ui_font_family: "read once at start-up, before any variable exists",
  encoder: "ENCODER_OPTIONS has a single value, so no selector was ever built",
  tickrate: "used only for tick maths",
  use_config_file_mode: "never referenced outside its own initialisation",
  tag_on_export: "derived from the first active tag, not an editable field",
  kill_mod_logic_mods: "forced to 'mixed'; no ANY/ALL/MIXED selector exists",
  kill_mod_logic_dp2: "forced to 'mixed'; no ANY/ALL/MIXED selector exists",
  kill_mod_logic_db: "forced to 'mixed'; no ANY/ALL/MIXED selector exists",
  kill_mod_no_trois_shot: "dead branch since kill_mod_trois_shot_exclude exists",
  kill_mod_no_trois_shot_req: "auto-generated; no Must box is ever built for it",
  kill_mod_high_velocity_exclude: "auto-generated; FERRARI PEEK builds no Exclude box",
  // Added in v213 with the confirmed process exit, after the inventory was
  // written. Read by the engine through _host_cfg; no widget was ever built.
  process_exit_poll_interval: "engine-only: how often the task list is polled",
  process_exit_timeout: "engine-only: how long the engine waits for cs2.exe to go",
  cs2_process_name: "engine-only: the image name the exit watcher looks for",
};

/** Has a control in Tkinter, not ported yet. MUST shrink at every chantier. */
export const NOT_YET_PORTED: readonly string[] = [
  "assemble_after",
  "assemble_output",
  "audio_bitrate",
  "audio_codec",
  "close_game_after",
  "clutch_1v1",
  "clutch_1v2",
  "clutch_1v3",
  "clutch_1v4",
  "clutch_1v5",
  "clutch_enabled",
  "clutch_mode",
  "clutch_wins_only",
  "concatenate_sequences",
  "crf",
  "cs2_cfg_dir",
  "cs2_send_to_back",
  "cs2_window_mode",
  "csdm_exe",
  "date_from",
  "date_to",
  "death_notices_duration",
  "delete_after_assemble",
  "dp2_threads",
  "ffmpeg_input_params",
  "ffmpeg_output_params",
  "framerate",
  "headshots_mode",
  "height",
  "hlae_afx_stream",
  "hlae_extra_args",
  "hlae_fix_scope_fov",
  "hlae_fov",
  "hlae_no_spectator_ui",
  "hlae_slow_motion",
  "kill_mod_ace",
  "kill_mod_ace_exclude",
  "kill_mod_ace_req",
  "kill_mod_airborne",
  "kill_mod_airborne_exclude",
  "kill_mod_airborne_req",
  "kill_mod_assisted_flash",
  "kill_mod_assisted_flash_exclude",
  "kill_mod_assisted_flash_req",
  "kill_mod_attacker_blind",
  "kill_mod_attacker_blind_exclude",
  "kill_mod_attacker_blind_req",
  "kill_mod_bully",
  "kill_mod_bully_exclude",
  "kill_mod_bully_n",
  "kill_mod_bully_req",
  "kill_mod_collateral",
  "kill_mod_collateral_exclude",
  "kill_mod_collateral_req",
  "kill_mod_eco_frag",
  "kill_mod_eco_frag_exclude",
  "kill_mod_eco_frag_req",
  "kill_mod_entry_frag",
  "kill_mod_entry_frag_exclude",
  "kill_mod_entry_frag_req",
  "kill_mod_flick",
  "kill_mod_flick_deg",
  "kill_mod_flick_exclude",
  "kill_mod_flick_req",
  "kill_mod_high_vel_thr",
  "kill_mod_high_velocity",
  "kill_mod_high_velocity_req",
  "kill_mod_hv_one_shot",
  "kill_mod_multi_kill",
  "kill_mod_multi_kill_exclude",
  "kill_mod_multi_kill_n",
  "kill_mod_multi_kill_req",
  "kill_mod_multi_kill_s",
  "kill_mod_no_scope",
  "kill_mod_no_scope_exclude",
  "kill_mod_no_scope_req",
  "kill_mod_one_tap",
  "kill_mod_one_tap_exclude",
  "kill_mod_one_tap_req",
  "kill_mod_one_tap_s",
  "kill_mod_savior",
  "kill_mod_savior_exclude",
  "kill_mod_savior_req",
  "kill_mod_spray_transfer",
  "kill_mod_spray_transfer_exclude",
  "kill_mod_spray_transfer_req",
  "kill_mod_through_smoke",
  "kill_mod_through_smoke_exclude",
  "kill_mod_through_smoke_req",
  "kill_mod_trois_shot",
  "kill_mod_trois_shot_exclude",
  "kill_mod_trois_shot_req",
  "kill_mod_trois_tap",
  "kill_mod_trois_tap_req",
  "kill_mod_wall_bang",
  "kill_mod_wall_bang_exclude",
  "kill_mod_wall_bang_req",
  "map_filter",
  "map_filter_enabled",
  "match_type_armsrace",
  "match_type_armsrace_alt",
  "match_type_casual",
  "match_type_competitive",
  "match_type_coop",
  "match_type_deathmatch",
  "match_type_demolition",
  "match_type_filter_enabled",
  "match_type_new_user",
  "match_type_premier",
  "match_type_retake",
  "match_type_skirmish",
  "match_type_training",
  "match_type_wingman",
  "output_dir_assembled",
  "output_dir_clips",
  "output_dir_concat",
  "pg_db",
  "pg_host",
  "pg_pass",
  "pg_port",
  "pg_user",
  "phys_blood",
  "phys_dynamic_lighting",
  "phys_ragdoll_enable",
  "phys_ragdoll_gravity",
  "phys_ragdoll_scale",
  "phys_sv_gravity",
  "player_name",
  "recsys",
  "show_only_death_notices",
  "show_xray",
  "steam_id",
  "subfolder_per_demo",
  "suicides_mode",
  "tag_enabled",
  "teamkills_mode",
  "theme_accent",
  "theme_bg",
  "true_view",
  "ui_remember_layout",
  "ui_split_pct",
  "ui_window_h",
  "ui_window_w",
  "video_codec",
  "video_container",
  "video_preset",
  "weapons",
  "width",
];
